language: php
php: 
  - 5.6
  - hhvm
before_script:
  - composer install
  - sudo add-apt-repository -y ppa:nginx/stable && sudo apt-get update
  - sudo apt-get install nginx -y
  - sudo ln -sfnv ~/.phpenv/versions/5.6/bin/php /usr/sbin/php5
  - sudo ln -sfnv ~/.phpenv/versions/5.6/sbin/php-fpm /usr/sbin/php5-fpm
script: phpunit
